[project]
name = "admin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.hatch.build]
packages = ["src/admin"]

[tool.uv]
package = false

[tool.uv.sources]
trailine_model = { workspace = true }
