[project]
name = "trailine-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.setuptools]
packages = ["trailine_model"]
package-dir = {"" = "src"}

[tool.hatch.build]
packages = ["src/model"]
