[project]
name = "trailine-server"
version = "0.1.0"
description = "트레일라인 서버 루트 프로젝트"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "api", "admin", "model", "scripts"
]